import type { CrmCredential } from "../crm-credential";

/**
 * Envelope-encryption boundary, per docs/08-security-observability-reliability.md
 * §1.2 ("CRM credentials use envelope encryption — a per-tenant Data
 * Encryption Key generated by AWS KMS, itself encrypted by a master Key
 * Encryption Key that never leaves KMS"). Kept behind a port, not called
 * directly against an AWS SDK client, for the same reason every other
 * environment-driven infrastructure choice in this codebase is (bcryptjs
 * over bcrypt, a local Redis over a managed one): this sandbox has no AWS
 * account/KMS access to verify against, so the concrete implementation
 * (infrastructure/aes-gcm-credential-encryptor.ts) is a local, real,
 * correctly-implemented AES-256-GCM stand-in — a genuine per-tenant-key
 * design (HKDF-derived from a master key + tenantId, so rotating one
 * tenant's key doesn't require touching another's), not a KMS API call.
 * Swapping in a real KMS-backed implementation later is an infrastructure
 * change behind this same port, not an application-layer rewrite.
 */
export interface CredentialEncryptor {
  encrypt(tenantId: string, credential: CrmCredential): Promise<Buffer>;
  decrypt(tenantId: string, ciphertext: Buffer): Promise<CrmCredential>;
}

export const CREDENTIAL_ENCRYPTOR = Symbol("CREDENTIAL_ENCRYPTOR");
